Traning started.....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Wating for data....
Traceback (most recent call last):
  File "start_traning.py", line 41, in <module>
    train(CONFIG_PATH, CONFIG, "cuda:0", train_loader_adversarial, val_loader_adversarial, val_loader)
  File "/srv/data/halmosi/ADVERSARIAL_TRANING_SEGMENTATION/AdversarialTraning/Trainer/Train.py", line 39, in train
    for data in train_loader_adversarial:
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1142, in _get_data
    success, data = self._try_get_data()
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
