
Traning started.....
Traceback (most recent call last):
  File "start_traning.py", line 41, in <module>
    train(CONFIG_PATH, CONFIG, "cuda:3", train_loader_adversarial, val_loader_adversarial, val_loader)
  File "/srv/data/halmosi/ADVERSARIAL_TRANING_SEGMENTATION/AdversarialTraning/Trainer/Train.py", line 44, in train
    prediction = model(image)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/segmentation_models_pytorch/base/model.py", line 16, in forward
    decoder_output = self.decoder(*features)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/segmentation_models_pytorch/unet/decoder.py", line 119, in forward
    x = decoder_block(x, skip)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/segmentation_models_pytorch/unet/decoder.py", line 41, in forward
    x = self.conv2(x)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 179, in forward
    self.eps,
  File "/srv/data/halmosi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 2283, in batch_norm
    input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 3; 23.69 GiB total capacity; 9.60 GiB already allocated; 162.75 MiB free; 9.70 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF